language: android
jdk:
    - oraclejdk7
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-22.0.1
    - android-22
    - add-on
    - extra
  licenses:
    - '.+'
addons:
  apt:
    packages:
    - libstdc++6:i386
    - lib32z1
    - build-essential
    - autoconf
    - automake
    - libtool
    - expect

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  # Install base Android SDK
    #- sudo apt-get update -qq
    #- sudo apt-get install -qq libstdc++6:i386 lib32z1 build-essential autoconf automake libtool expect
    - curl -L http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2 > ndk.tar.bz2
    - tar -C /tmp -jxf ndk.tar.bz2
    - export NDK_PROJECT_PATH=$PWD
install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
    - make -C external NDK=/tmp/android-ndk-r9
    - ./gradlew clean assembleDebug
